name: flutter_draw_appp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  file_picker: ^6.1.1
  file_saver: ^0.2.9
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_hooks: ^0.20.4
  flutter_painter_v2: ^2.0.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.7
  phosphor_flutter: ^2.0.1
  universal_html: ^2.2.4
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
